###########################################################################
#
# Generated by : Version 11.0 Build 208 07/03/2011 Service Pack 1 SJ Web Edition
#
# Project      : CII_Starter_USB_API
# Revision     : CII_Starter_USB_API
#
# Date         : Mon Dec 12 10:57:44 GMT 2011
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: TCK
create_clock -period "2.500 ns" \
             -name {TCK} {TCK}
# ---------------------------------------------


# Original Clock Setting Name: CLOCK_50
create_clock -period "20.000 ns" \
             -name {CLOCK_50} {CLOCK_50}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------



# ---------------------------------------------
# The following clock group is added to try to 
# match the behavior of:
#   CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS = ON
# ---------------------------------------------

set_clock_groups -asynchronous \
                 -group { \
                       CII_Starter_USB_API:inst|Multi_Sdram:u3|Sdram_Controller:u1|PLL1:sdram_pll1|altpll:altpll_component|_clk0 \
                       CII_Starter_USB_API:inst|Multi_Sdram:u3|Sdram_Controller:u1|PLL1:sdram_pll1|altpll:altpll_component|_clk2 \
                       CLOCK_50 \
                        } \
                 -group { \
                       TCK \
                        } \

# ---------------------------------------------

